// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-FvnVtrJUNr7CFqRX3pTv9ktO1pfp89c',
    appId: '1:748099660438:web:3f3dc36021c9d8a45df0b7',
    messagingSenderId: '748099660438',
    projectId: 'sqlplayground-a93a2',
    authDomain: 'sqlplayground-a93a2.firebaseapp.com',
    databaseURL: 'https://sqlplayground-a93a2-default-rtdb.firebaseio.com',
    storageBucket: 'sqlplayground-a93a2.firebasestorage.app',
    measurementId: 'G-F94MSH5ES0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjC_piVJUAmHDVUYdPCdHz9VhHvxEfOww',
    appId: '1:748099660438:android:544fc9c3134bcf6d5df0b7',
    messagingSenderId: '748099660438',
    projectId: 'sqlplayground-a93a2',
    databaseURL: 'https://sqlplayground-a93a2-default-rtdb.firebaseio.com',
    storageBucket: 'sqlplayground-a93a2.firebasestorage.app',
  );
}
